FROM ubuntu:16.04
RUN apt-get update && \
	apt-get install nano mc wget openssh-server -y
RUN mkdir /var/run/sshd && \
	echo 'root:umszki123!' | chpasswd && \
	sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
	sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profileRUN useradd -ms /bin/bash -p level0 level0

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
